### ISSUE TITLE
Cannot remove a deleted IoTProcessor from IoTProcessorManagementState 

### ISSUE THREAD

**Issue by Banchio** [Azure-Samples/service-fabric-dotnet-iot#1]
When we use the Remove-IoTProcessor with our IoTProcessor (ex. test1) after a while we correctly see the status as "Provisioned Deleted". Now if we try to import a new one with the same name it fails. The only way to remove the IoTProcessor from the list is, obviously, to destroy and recreate the application IoTProcessorManagement.
Apart this, the architecture and code for this sample is awesome, thanks a lot!

**Comment by khenidak** [comment]
Thanks!
i actually thought about completely deleting the IoTProcessor & the definition,  I figured if we remove the definition you lose all traces of it in the system. Which makes "where did my events go"  an impossible question to answer. I will keep the comments in mind for later phases. Maybe we can copy the IoTProcessor definition somewhere else (i.e. different reliable dictionary, external store) for tracking then deleting it locally.

**Comment by vturecek** [comment]
Closing this as the latest version of this sample doesn't have these PS commands.
