### ISSUE TITLE
Enqueue in AddBufferedWorkItemAsync thorws exception.

### ISSUE THREAD

**Issue by pvbinu** [Azure-Samples/service-fabric-dotnet-iot#13]
On enqueuing a work item of type IWorkItem to Reliable collection is throwing a serialization exception. 

I also put a query in StackOverflow as well regarding this. 

> http://stackoverflow.com/questions/39343161/ireliablequeue-enqueue-serialization-error

**Comment by masnider** [comment]
Looks like this was answered on SO. Can you close the issue if the solution worked for you?

**Comment by pvbinu** [comment]
When changed IWorkItem to a concrete type , it worked.
