### ISSUE TITLE
Issue when resuming a Processor

### ISSUE THREAD

**Issue by Banchio** [Azure-Samples/service-fabric-dotnet-iot#3]
When resuming a Processor, the Resume method should call RefreshListenersAsync instead of ClearListenersAsync. I wanted to create another PR but apparently I'm not able to do that so I'm inserting the issue here.

**Comment by masnider** [comment]
@Banchio weird you can't create another PR. Maybe you'd need another separate branch to do so? @khenidak - something else to check out.

**Comment by khenidak** [comment]
You are right, it should refresh the listeners, the original thought that listeners config might have changed between between pausing and resuming the worker hence the need refresh them. 

as for creating PR. I am not sure why you can't is this a Git Hub issue?
