### ISSUE TITLE
Debugging with visual studio

### ISSUE THREAD

**Issue by AmirSasson** [Azure-Samples/service-fabric-dotnet-iot#32]
Anybody know how to debug / attach debugger?
when creating a "old school" service fabric app from visual studio template (with dotnet 4.6.2 as the build tools), when hitting f5 everything is magically works and you able to debug.
any chance i would be able to debug on local cluster this repo?

**Comment by masnider** [comment]
It is the normal "attach to process" flow from within Visual Studio: https://docs.microsoft.com/en-us/visualstudio/debugger/attach-to-running-processes-with-the-visual-studio-debugger
