### ISSUE TITLE
PowerShell console message not outputting correctly

### ISSUE THREAD

**Issue by godlikesme** [Azure-Samples/service-fabric-dotnet-iot#7]
In the IoTProcessorManagement.InternalFunctions.cs file, method SendToEventsToEventHubAsync has the following code.

The Console.WriteLine portion will only execute once because the method is async. Therefore the user will only see "sending message #1/10" and not "sending message #2/10...3/10...4/10 etc.".

            do
            {
                var Event = new
                {
                    DeviceId = PublisherName,
                    FloorId = string.Concat("f", rand.Next(1, 10).ToString()),
                    BuildingId = string.Concat("b", rand.Next(1, 10).ToString()),
                    TempF = rand.Next(1, 100).ToString(),
                    Humidity = rand.Next(1, 100).ToString(),
                    Motion = rand.Next(1, 10).ToString(),
                    light = rand.Next(1, 10).ToString(),
                    EventDate = DateTime.UtcNow.ToString()
                };

                // Powershell redirects stdout to PS console.
                Console.WriteLine(
                    string.Format("sending message# {0}/{1} for Publisher {2} Hub:{3}", current, NumberOfMessages, PublisherName, HubDefinition.EventHubName));
                EventData ev = new EventData(Encoding.UTF8.GetBytes(JsonConvert.SerializeObject(Event)));
                ev.SystemProperties[EventDataSystemPropertyNames.Publisher] = PublisherName;
                await eventHubClient.SendAsync(ev);
                current++;
            } while (current <= NumberOfMessages);

**Comment by vturecek** [comment]
Closing this, as the newest version of this sample doesn't have this.
