### ISSUE TITLE
IotProcessorManagement Post Build events

### ISSUE THREAD

**Issue by LZorglub** [Azure-Samples/service-fabric-dotnet-iot#8]
Hi thanks for the samples,
In the IoTProcessorManagement project, in the PostBuild events better to replace : 
xcopy /y $(TargetDir)*.* $(TargetDir)PowerShell\
by 
xcopy /y "$(TargetDir)*.*" "$(TargetDir)PowerShell\"

Better to keep quote if project is unzip inside ...\Documents\Visual Studio 2015\....
Regards

**Comment by vturecek** [comment]
closing this out, the newest version of the sample uses a different build script.
